api_login:
    path: /api/login
    controller: App\Controller\AuthController::login
    methods: [POST]
api_register:
    path: /api/register
    controller: App\Controller\AuthController::register
    methods: [POST]
api_list_orders:
    path: /api/orders
    controller: App\Controller\OrderController::listOrders
    methods: [GET]
api_cancel_order:
    path: /api/orders/{id}/cancel
    controller: App\Controller\OrderController::cancelOrder
    methods: [DELETE]
